events {}
http {
    server {
        listen 443 ssl;
        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        # Habilitar mTLS
        ssl_client_certificate /etc/nginx/certs/ca.crt; # CA de confianza
        ssl_verify_client      on;                      # Requerir certificado de cliente

        location / {
            return 200 "Autenticación con mTLS exitosa!\n";
        }
    }
}